### ISSUE TITLE
[BUG]: "i18next.init is not a function" with v1.1.27

### ISSUE THREAD

**Issue by smlimasu** [compodoc/compodoc#1642]
##### **Overview of the issue**
*sorry, must be v1.1.27 in the title ofc.
After installing Compodoc 1.1.27 (so happy that we finally have a release), the following error about i18next appears when trying to start storybook (9.1.3) or compodoc standalone documentation. 

This error lets the build/serve fail, and storybook build/serve, too. 

##### **Operating System, Node.js, npm, compodoc version(s)**

1.1.27

TypeScript version used by Compodoc : 5.8.3

Node.js version : v22.17.1

Operating system : Linux 6.6

Angular 19.2.15

##### **If possible your terminal logs before the error**

CLI Error: 
TypeError: i18next.init is not a function

##### **Reproduce the error**

Install Compodoc 1.1.27 and try to build/serve, same with storybook.

**Comment by kcinay055679** [comment]
same problem here

**Comment by vogloblinsky** [comment]
I am on init right now

**Comment by smlimasu** [comment]
@vogloblinsky i see 2 commits, the first adds the .default and the second removes it. 

Adding the .default again solves the bug for me in 1.1.28 - with i18next 25.5.1

**Comment by fank** [comment]
Issue still exists with 1.1.28:
```
...
[11:12:36] TypeError: i18next.init is not a function
[11:12:36] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
Error: Process completed with exit code 1.
```

**Comment by dalux-jer** [comment]
I'm using compodoc with storybook 9.1.3 and Angular 20.1.1.
In my case storybook works with compodoc 1.1.27 and 1.1.28, but fails in 1.1.29 with the following error

```
Compodoc v1.1.29
[14:26:49] TypeError: Cannot read properties of undefined (reading 'init')
[14:26:49] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)                                                                                                                                
ELIFECYCLE  Command failed.
```

**Comment by vogloblinsky** [comment]
@fank and with 1.1.29 ?

**Comment by fank** [comment]
@vogloblinsky works!
```
[12:48:15] Process menu...
[12:48:16] Copy main resources
[BABEL] Note: The code generator has deoptimised the styling of /home/runner/work/negsoft-gui/negsoft-gui/node_modules/@compodoc/compodoc/dist/menu-wc_es5.js as it exceeds the max of 500KB.
[12:48:16] Documentation generated in compodoc/documentation/ in 51.449 seconds using gitbook theme
```

**Comment by vogloblinsky** [comment]
@jerAtDalux 
can i have all your terminal steps to reproduce your issue ?

**Comment by dalux-jer** [comment]
I'm in a large monorepo and I'm in the process of adding storybook for documentation of our design system. I can share the script to run storybook and the angular.json configuration of compodoc within storybook

Launching storybook
`ng run docs:storybook --no-open`

angular.json

```
{
  ...
   "projects": {
      ...
      "docs": {
        ...
        "architect": {
          "storybook": {
          "builder": "@storybook/angular:start-storybook",
          "options": {
            "configDir": "docs/.storybook",
            "browserTarget": "docs:build",
            "compodoc": true,
            "compodocArgs": [
              "-t",
              "--disablePrivate",
              "--disableProtected",
              "--disableCoverage",
              "--disableInternal",
              "--disableLifeCycleHooks",
              "--disableDependencies",
              "-e",
              "json",
              "-d",
              "docs"
            ],
            ...
        }
    }
}
```

**Comment by ahaavila** [comment]
For me didn't work with version 1.1.29.
It gives me this error now:
 TypeError: Cannot read properties of undefined (reading 'init')

<img width="1826" height="126" alt="Image" src="https://github.com/user-attachments/assets/0a328d2c-ca0f-4b50-8f61-09f3da4d45bf" />

**Comment by vogloblinsky** [comment]
Fixed in 1.1.30

**Comment by ahaavila** [comment]
@vogloblinsky Thanks, now it is working fine :)
